# basic options
title: DeePaint
title-icon: fas fa-code
# description, keywords, and image for meta tags
featured-image: "/img/homeBilkent.jpg"
email: bilkent-cs-senior-deepaint@googlegroups.com
description: Department of Computer Engineering

# Build settings
markdown: kramdown
theme: minima
